INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Claudia',  '7500.00', NULL );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Andre'  ,  '8300.00', 'Claudia' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Marta'  ,  '7800.00', 'Andre' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Sandro' ,  '8100.00', 'Andre' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Luis'   ,  '7200.00', 'Sandro' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Marcos' ,  '8100.00', 'Sandro' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Luana'  ,  '5200.00', 'Andre' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Pedro'  ,  '9200.00', 'Claudia' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Nanci'  ,  '8300.00', 'Claudia' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Paula'  ,  '6900.00', 'Nanci' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Andreia',  '8100.00', NULL );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Fabio'  ,  '7800.00', 'Andreia' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Raquel' ,  '7100.00', 'Fabio' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Sandra' ,  '8400.00', 'Andreia' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Ana'    ,  '6800.00', 'Sandra' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Silvia' ,  '8900.00', 'Sandra' );
INSERT INTO organizacao ( nome, vendas, superior ) VALUES ( 'Rodrigo',  '8900.00', NULL );
